### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by marcstee** [hivivo/ngx-json-viewer#16]
Is it possible to change default styles? Mainly colors.

**Comment by benkrig** [comment]
@marcstee,

It doesn't look like there's any built-in, clean way to change color styling. This seems like a good area for future development.
Until there's an official development for this, I've added a workaround to achieve this with Sass below. You can change the colors to suit your needs.

```scss
// add this to your component's .scss
$type-colors: (
  string: #0bff00,
  number: #009688,
  boolean: #b938a4,
  date: #05668D,

  array: #999,
  object: #999,
  function: #999,

  'null': #fff,
  undefined: #fff
);

@each $type, $color in $type-colors {
  ::ng-deep .segment-type-#{$type} > .segment-main > .segment-value {
    color: $color !important;
  }
}
```

Keep in mind this uses `::ng-deep` which is moving towards depreciation. Although this is listed as depreciated in [official documentation](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep), there are no plans to officially remove it anytime in the future. See https://github.com/angular/angular/issues/7562 for more on that.
